# Generated by Django 3.2.6 on 2021-09-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Konu Başlığı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('isPublished', models.BooleanField(default=True)),
            ],
        ),
    ]
